INSERT INTO COURSE(ID_COURSE, NAME,DESCRIPTION, CODE) VALUES (1,'CALCULO 1', 'CALCULO 01', 'C001');
INSERT INTO COURSE(ID_COURSE, NAME,DESCRIPTION, CODE) VALUES (2,'ALGORITMICA 1', 'ALGORITMICA 1', 'A001');
INSERT INTO COURSE(ID_COURSE, NAME,DESCRIPTION, CODE) VALUES (3,'ALGORITMICA 2', 'ALGORITMICA 2', 'A002');

INSERT INTO STUDENT(ID_STUDENT, CODE,NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES (1,'S001', 'ALVARO', 'CHAVEZ', 'email@gmail.com', CURRENT_DATE );
INSERT INTO STUDENT(ID_STUDENT, CODE,NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES (2,'S002', 'JOSE', 'RAMIREZ', 'email2@gmail.com',CURRENT_DATE );

INSERT INTO TEACHER(ID_TEACHER, CODE, NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES (1,'P001', 'MIGUEL', 'FUENTES', 'email3@gmail.com',CURRENT_DATE );
INSERT INTO TEACHER(ID_TEACHER, CODE, NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES (2,'P002', 'JESUS', 'ROMERO', 'email4@gmail.com',CURRENT_DATE );

